version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: snyk
    versions:
    - 1.439.3
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.462.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.478.0
    - 1.491.0
    - 1.503.0
    - 1.509.0
    - 1.514.0
    - 1.521.0
    - 1.526.0
    - 1.528.0
    - 1.530.0
    - 1.532.0
    - 1.541.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: pm2
    versions:
    - 4.5.4
  - dependency-name: systeminformation
    versions:
    - 4.34.7
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: underscore
    versions:
    - 1.12.0
  - dependency-name: xo
    versions:
    - 0.37.1
  - dependency-name: cassandra-driver
    versions:
    - 4.6.1
  - dependency-name: ioredis
    versions:
    - 4.19.4
  - dependency-name: less
    versions:
    - 4.1.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine3.11
    - 15.11.0.pre.alpine3.11
    - 15.12.0.pre.alpine3.11
    - 15.13.0.pre.alpine3.11
    - 15.14.0.pre.alpine3.11
    - 15.7.0.pre.alpine3.11
    - 15.8.0.pre.alpine3.11
    - 15.9.0.pre.alpine3.11
